# Generated by Django 5.0.4 on 2024-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkloads',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capacitorbank',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dgset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genstation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lines',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lines',
            name='pssc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='reactor',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stntransformer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transformer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='substation_master',
            name='updated_dt',
            field=models.DateField(blank=True),
        ),
    ]
