# Generated by Django 5.0.4 on 2024-08-27 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttpapp', '0002_bulkloads_deleted_bus_deleted_capacitorbank_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stntransformer',
            old_name='feed_vol',
            new_name='ict_capacity',
        ),
        migrations.RemoveField(
            model_name='stntransformer',
            name='teritory_volt',
        ),
        migrations.AddField(
            model_name='lines',
            name='modifieddt',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
