# Generated by Django 5.0.4 on 2024-09-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttpapp', '0004_addedbulkloads_addedcapacitorbank_addedlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedbulkloads',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedcapacitorbank',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedlines',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedreactor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addedtransformer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
